name: MinePayApiDemo
version: Release 2.0.0
main: top.minepay.example.MinePayApiDemo
api-version: 1.13
depend: [ MinePay ]
authors: [ Peter1303, Ranica ]
description: MinePay API 使用
website: https://minepay.top/

commands:
  mpdm:
    description: minepay_demo
    usage: /<command>